######################################################################
# Automatically generated by qmake (3.0) Sun Aug 25 15:46:24 2019
######################################################################

TEMPLATE = app
TARGET = Tetris
INCLUDEPATH += .
QT += widgets
CONFIG += c++11

# Input
SOURCES += Tetris.cpp
